// posts
export const ADD_POST = 'ADD_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const INCREMENT_VOTE_COUNT = 'INCREMENT_VOTE_COUNT';
export const DECREMENT_VOTE_COUNT = 'DECREMENT_VOTE_COUNT';

// comments
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const INCREMENT_COMMENT_VOTE_COUNT = 'INCREMENT_COMMENT_VOTE_COUNT';
export const DECREMENT_COMMENT_VOTE_COUNT = 'DECREMENT_COMMENT_VOTE_COUNT';

// filtering and sorting
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';

// server data requests
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const RECEIVE_POST_DETAILS = 'RECEIVE_POST_DETAILS';
export const RECEIVE_COMMENT_DETAILS = 'RECEIVE_COMMENT_DETAILS';
