// categories
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

// comments
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const UPVOTE_COMMENT_REQUEST = 'UPVOTE_COMMENT_REQUEST';
export const DOWNVOTE_COMMENT_REQUEST = 'DOWNVOTE_COMMENT_REQUEST';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const UPVOTE_COMMENT_SUCCESS = 'UPVOTE_COMMENT_SUCCESS';
export const DOWNVOTE_COMMENT_SUCCESS = 'DOWNVOTE_COMMENT_SUCCESS';

// posts
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const UPVOTE_POST_REQUEST = 'UPVOTE_POST_REQUEST';
export const DOWNVOTE_POST_REQUEST = 'DOWNVOTE_POST_REQUEST';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const UPVOTE_POST_SUCCESS = 'UPVOTE_POST_SUCCESS';
export const DOWNVOTE_POST_SUCCESS = 'DOWNVOTE_POST_SUCCESS';

export const FETCH_ALL_POSTS_REQUEST = 'FETCH_ALL_POSTS_REQUEST';
export const FETCH_CATEGORY_POSTS_REQUEST = 'FETCH_CATEGORY_POSTS_REQUEST';
export const FETCH_POST_COMMENTS_REQUEST = 'FETCH_POST_COMMENTS_REQUEST';

export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';
export const FETCH_CATEGORY_POSTS_SUCCESS = 'FETCH_CATEGORY_POSTS_SUCCESS';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';

// navigation
export const ADD_NEW_POST = 'ADD_NEW_POST';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';


// // posts
// export const ADD_POST = 'ADD_POST';
// export const EDIT_POST = 'EDIT_POST';
// export const DELETE_POST = 'DELETE_POST';
// export const UPVOTE_POST = 'UPVOTE_POST';
// export const DOWNVOTE_POST = 'DOWNVOTE_POST';

// export const FETCH_ALL_POSTS_REQUEST = 'FETCH_ALL_POSTS_REQUEST';
// export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';

// export const FETCH_CATEGORY_POSTS_REQUEST = 'FETCH_CATEGORY_POSTS_REQUEST';
// export const FETCH_CATEGORY_POSTS_SUCCESS = 'FETCH_CATEGORY_POSTS_SUCCESS';

// // comments
// export const ADD_COMMENT = 'ADD_COMMENT';
// export const EDIT_COMMENT = 'EDIT_COMMENT';
// export const DELETE_COMMENT = 'DELETE_COMMENT';
// export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
// export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT';

// export const FETCH_POST_COMMENTS_REQUEST = 'FETCH_POST_COMMENTS_REQUEST';
// export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';

// // categories
// export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
// export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
